# Scientific Programming in Python - Dictionaries and Functions

###Problem 1. Library, with dictionaries

We’ll revisit the Problem 3 of Assignment 2, where we had to manipulate some data from a fake
library.

In this problem, we had the following format for the data:


In [1]:
[[123456,312314,531337],                     # Student IDS
 ['John Doe',' Jane Miller','Ted Johnson'],  # Student Names
 [1.49,0.00,8.12]]                           # Amounts owed

[[123456, 312314, 531337],
 ['John Doe', ' Jane Miller', 'Ted Johnson'],
 [1.49, 0.0, 8.12]]

>**(a)** Construct a dictionary to store this data, using the student ID (the ﬁrst big number) as the **key**, and the amount owed as the **values**. 

> Use the code below to get you started. You can type the key, value pairs into the curly brackets `{ }`.

In [2]:
student_id_to_amount_owed = {123456: 1.49, 312314: 0.00,531337: 8.12}  # complete this line to include all the student IDs and amounts owed
print student_id_to_amount_owed

{123456: 1.49, 531337: 8.12, 312314: 0.0}


> **(b)** Use this dictionary to find out how much money the student with id `531337` owes. 

> You should use square brackets `[ ]` to index into your dictionary.


In [3]:
print(student_id_to_amount_owed[531337])

8.12


> Try also finding out how much 123456 owes. What about newly enrolled student 999888?

In [4]:
amount_owed_by_531337 = student_id_to_amount_owed
print (amount_owed_by_531337)

print(student_id_to_amount_owed[999888])

{123456: 1.49, 531337: 8.12, 312314: 0.0}


KeyError: 999888

> **(c)** Create another dictionary which maps the name of the student to its student id.  This time, instead of typing the values in by hand, fill in this dictionary by looping over the list `student_names_and_ids` given below:


In [5]:
student_names_and_ids = [('John Doe', 123456), ('Jane Miller', 312314), ('Ted Johnson', 531337)]

studentname_to_id = {}  # initialise empty dictionary

for name, sid in student_names_and_ids:
    studentname_to_id[name] = sid

print studentname_to_id
# desired output : {'Jane Miller': 312314, 'John Doe': 123456, 'Ted Johnson': 531337}

{'Jane Miller': 312314, 'Ted Johnson': 531337, 'John Doe': 123456}



> **(c)** Print how much money 'John Doe' owes the library, using both of your dictionaries. 

>  *(Hint: First find out John Doe's student ID, then use this to find out how much he owes)*

In [6]:
John_doe_balance = student_id_to_amount_owed[studentname_to_id['John Doe']]
print(John_doe_balance)

1.49


> **(d)** Create the list of the names of students owing more than £1.0 to the library.

> *(Hint: If it is easier, first make a list of all the student IDs which owe more than £1.0 Then adapt the code to create a list of names instead).*


In [8]:
bad_students = [] 

for sid, val in student_id_to_amount_owed.items():
    if val > 1.0:
        for nm, ssid in student_names_and_ids:
            if sid == ssid:
                bad_students.append(nm)

print (bad_students)

['John Doe', 'Ted Johnson']


###Problem 2. Counting words

>**(a)** In this problem we’ll use the text of Alice in Wonderland to construct dictionaries counting the
number of times particular words and pairs of words appear.

In [301]:
import urllib2
URL = "http://www.gutenberg.org/files/11/11.txt"
f = urllib2.urlopen(URL)
open("alice.txt","w").write(f.read())

This will create a new file called "alice.txt"

>**(b)** We'll process alice.txt in loops like this:

In [152]:
f = open("alice.txt", "r")

words = {}

for line in f.readlines():
     for word in line.strip().split():
        if word not in words:
            words[word] = 1
        else:
        #elif word in words:
            words[word] = words[word]+1


print[words]

[{"figure!'": 1, 'four': 6, 'hanging': 3, 'ringlets': 1, "story!'": 2, 'Foundation': 14, 'IX.': 1, "'Shall": 1, 'dear!"': 1, "dear!'": 3, 'wood,': 1, 'wood.': 3, 'advice,': 1, 'screaming': 1, 'prize': 1, 'wooden': 1, 'further:': 1, 'persisted': 1, 'her.': 13, 'tired': 7, "ears--'": 1, 'BEG': 1, 'chin:': 1, 'her;': 3, 'her:': 5, 'second': 6, 'audibly.': 1, 'chin.': 2, "'You": 30, 'accessed,': 1, 'increasing': 1, 'is--"The': 1, "impertinent,'": 1, 'glass;': 1, "so.'": 1, 'reasons.': 1, 'here': 14, 'fire,': 3, "'THAT": 2, 'glass.': 1, 'glass,': 2, 'hers': 3, 'shriek': 3, 'finger;': 1, 'pieces.': 1, 'barrowful': 2, 'NOT': 7, 'golden': 7, 'owed': 1, 'words:--': 2, 'then--always': 1, 'replace': 1, 'brought': 3, "Caterpillar's": 1, "sea,'": 1, 'spoke': 4, 'Indeed,': 1, 'until': 4, 'dry,': 1, 'paperwork': 1, 'hurt': 2, 'glass': 4, '90': 2, 'hold': 7, 'sorry': 1, 'liability,': 1, 'laughter.': 1, '"THEY': 1, 'NOTICE': 1, 'unjust': 1, 'organized': 1, 'shore.': 1, 'shore,': 2, "liked.'": 1, "that.

>**(b)** How many times does the word “the” appear? What about the word “The”?

In [47]:
print(words['the'])
print(words['The'])

1664
100


>**(d)** Modify the code so words are counted independent of whether they are made of upper or
lower case letters. i.e., “the”, “The” and “tHE” are all treated as the same word.


In [ ]:
f = open("alice.txt", "r")

words = {}

for line in f.readlines():
     for word in line.strip().split():
        if word.lower() not in words:
            words[word.lower()] = 1
        elif word.lower() in words:
            words[word.lower()] = words[word.lower()]+1


print[words]

>**(e)** Repeat the previous exercise, but instead of counting the number of times a word appears,
count the number of times pairs of words appear. You might ﬁnd it useful to store the
previous word in a variable.

In [48]:
f = open("alice.txt", "r")

words = {}
prev_wd = ''

for line in f.readlines():
     for word in line.strip().split():
        if word.lower() + ' ' + prev_wd.lower() not in words:
            words[word.lower() + ' ' + prev_wd.lower()] = 1
        elif word.lower() + ' ' + prev_wd.lower() in words:
            words[word.lower() + ' ' + prev_wd.lower()] = words[word.lower() + ' ' + prev_wd.lower()]+1
        prev_wd = word

print[words]

[{'my dinah': 1, "generally 'it's": 1, 'but character,': 1, 'the displaying': 1, "muttered it?'": 1, 'complying without': 1, "think can't": 1, 'uncomfortable. very': 1, 'eaglet, an': 1, 'very get': 1, "nothing 'you're": 1, 'a croquet-ground': 1, 'alice plate.': 1, 'tasted never': 1, "said caucus-race?'": 1, 'you see': 2, 'be stuff?': 1, 'hunting after': 1, 'first--they together': 1, 'how think': 1, 'any it': 1, 'puzzling on': 1, 'opened, house': 1, 'pink with': 1, 'settled it': 1, 'confusion such': 1, 'would you': 2, 'he all:': 1, 'fact, in': 2, 'to knew)': 1, 'any in': 5, 'implied certain': 1, 'about more': 1, 'her forgetting': 1, 'or come,': 1, "down,' sit": 1, 'without allow': 1, 'the protect': 2, 'herself find': 2, 'sky! the': 1, 'the persisted': 1, 'usually you': 1, "'but sight:": 1, 'to found': 1, "manage i'll": 1, 'turtle--we old': 1, 'links active': 2, 'was door': 1, 'down got': 1, 'http://pglaf.org/donate visit:': 1, '\'ugh!\' northumbria--"\'': 1, 'sit but': 1, 'under distrib

>**(f)** What are the most common words and pairs of words in Alice in Wonderland?<br> You might find the *sorted* function or the *sort* function for lists to be useful.


In [67]:
# hint: example of how you use sorted
x = [1,4,2,7,5,6,3]
print x
#print sorted(x),type(sorted(x)) # outputs a list
#print sort(x),type(sort(x))  # outputs a numpy.ndarray

#print sorted([words]) , type(sorted([words]))

sorted( ((wd,ct) for ct,wd in words.iteritems()), reverse=True)  #  the iteritems combined with for and reverse order of wd/ct means it will sort in the value rather than key.

[1, 4, 2, 7, 5, 6, 3]


[(207, 'the said'),
 (154, 'the of'),
 (101, 'a in'),
 (92, 'the in'),
 (84, 'the to'),
 (80, 'the and'),
 (63, 'the at'),
 (60, 'she as'),
 (57, 'had she'),
 (57, '* *'),
 (55, 'was it'),
 (54, 'little a'),
 (54, 'gutenberg-tm project'),
 (53, 'mock the'),
 (51, 'was she'),
 (50, 'the with'),
 (49, 'she and'),
 (49, 'be to'),
 (39, 'to said'),
 (38, 'alice, said'),
 (37, 'the on'),
 (37, 'of out'),
 (34, 'was there'),
 (33, 'turtle mock'),
 (33, 'alice. said'),
 (32, 'she that'),
 (31, 'queen the'),
 (31, 'a was'),
 (30, 'the all'),
 (29, 'the by'),
 (29, 'she so'),
 (29, 'project the'),
 (29, 'march the'),
 (28, 'went she'),
 (28, 'said she'),
 (28, 'king the'),
 (27, 'this of'),
 (27, 'not did'),
 (27, 'alice said'),
 (27, 'a with'),
 (27, 'a such'),
 (26, 'you if'),
 (25, 'very a'),
 (25, 'herself, to'),
 (24, 'then and'),
 (24, 'the into'),
 (24, 'a of'),
 (23, 'the for'),
 (23, 'see to'),
 (23, 'on went'),
 (23, 'it that'),
 (22, 'white the'),
 (22, 'she but'),
 (22, 'of one'),
 

### Problem 4. ArgMax and ArgSort

>**(a)** Finding the index of the largest (or smallest) element in a list is a commonly needed opera-
tion, but Python does not provide this function in its standard library (numpy will provide those). Write two functions


In [98]:
def argmax(list_input):
    last_num = list_input[0]
    last_ind = 0
    for index, num in enumerate(list_input):
        if num > last_num:
            last_num = num
            last_ind = index
    print(last_ind)
    
def argmin(list_input):
    last_num = list_input[0]
    last_ind = 0
    for index, num in enumerate(list_input):
        if num < last_num:
            last_num = num
            last_ind = index
    print(last_ind)
    

>that return the index of the largest and smallest element in the list *list_input* respectively. Example output:


    >>> list1 = [1,3,2,6,0,2,3,4,5]
    >>> argmax(list1)
    3
    >>> argmin(list1)
    4

In [99]:
# try it here
list1 = [1,3,2,6,0,2,3,4,5]
argmax(list1)
argmin(list1)

3
4


>**(b)** **(extra)** Instead of just finding the index of the largest or smallest element, one might be interested in the entire list of indices that would sort the list. In one of the previous exercises we presented you with this piece of code for finding the indices that sort a list.


In [93]:
l = [1,3,2,6,0,2,3,4,5]
zip(*sorted(zip(l, range(len(l)))))[1]

(4, 0, 2, 5, 1, 6, 7, 8, 3)

>It works by combining the list with the list of indices, sorting the combined list, and then untangling the results. Have a look at the documentation of the *zip* function to understand how it works. Write a function:

In [100]:
def argsort(l):
    return zip(*sorted(zip(l, range(len(l)))))[1]

>that returns the list of indices that would sort the list, but instead of using the hard to read
line above that uses zip, use list comprehensions. Example output:

    >>> l = [1,3,2,6,0,2,3,4,5]
    >>> argsort(l)
    [4, 0, 2, 5, 1, 6, 7, 8, 3]
    >>> [l[i] for i in argsort(l)]
    [0, 1, 2, 2, 3, 3, 4, 5, 6]


In [101]:
# try it here
l = [1,3,2,6,0,2,3,4,5]
print argsort(l)
print [l[i] for i in argsort(l)]

(4, 0, 2, 5, 1, 6, 7, 8, 3)
[0, 1, 2, 2, 3, 3, 4, 5, 6]


### Problem 5. Simple ciphers


Suppose you wish to send your friend a message, and if someone happens to look at it, you do not want them to know what it says.<br>
A simple way of doing this is to replace each letter, with
a different one.<br>
For example, suppose I wish to send the phrase “dancing is silent poetry”.<br>
By exchanging each letter with another, we can encode this as: “robqwbu wg gwzsbh dcshfm”.

>**(a)** Write a function that swaps the letter in a string according to a dictionary. For example:


In [302]:
def swapdict(string, dic):
    str_len = len(string)
    output = ''
    for i in range(str_len):
        if string[i] in dic:
            output += str(dic[string[i]])
            #print dic[string[i]]
        else:
            output += string[i]
            #print string[i]
    
    return (output)    

    >>> print swapdict('hello', {'e': 'i'})
    hillo
    >>> print swapdict('hello', {'l': 'w'})
    hewwo
    >>> print swapdict('hello', {'l': 'm', 'h': 'p', 'e': 'o', 'o': 'e'})
    pomme

In [303]:
# your code here
print swapdict('hello', {'e': 'i'})

hillo


>**(b)** Write a function that generates a dictionary whose keys are letters of the alphabet, and whose values are those letters shifted along by a given number of letters.


In [236]:
def shiftdict(i):
    from string import ascii_lowercase
    key_list = list(ascii_lowercase)
    val_list = []

    #i=3

    for index, ref in enumerate(key_list):
        if i + index > 25:

            val_list.append(key_list[((i + index)-26)])
            #print key_list[(i + index)-26]
        else:
            val_list.append(key_list[(i + index)])
            #print key_list[(i + index)]

    t = zip(key_list, val_list)

    #print t

    otp_dict = dict((y, x) for y, x in t)
    return otp_dict



    >>> print shiftdict(0)
    {'a': 'a', 'b': 'b', ..., 'z': 'z'}
    >>> print shiftdict(3)
    {'a': 'd', 'b': 'e', ..., 'z': 'c'}
    >>> print shiftdict(13)
    {'a': 'n', 'b': 'o', ..., 'z': 'm'}

>In the first case, the letters are not shifted, because the argument to *shiftdict* is zero. In the second case, letters are shifted along by three letters: “a” is the first letter, and “d” is the forth letter, and so key “a” points to letter “d”.

In [237]:
# try it here
print shiftdict(3)

{'a': 'd', 'c': 'f', 'b': 'e', 'e': 'h', 'd': 'g', 'g': 'j', 'f': 'i', 'i': 'l', 'h': 'k', 'k': 'n', 'j': 'm', 'm': 'p', 'l': 'o', 'o': 'r', 'n': 'q', 'q': 't', 'p': 's', 's': 'v', 'r': 'u', 'u': 'x', 't': 'w', 'w': 'z', 'v': 'y', 'y': 'b', 'x': 'a', 'z': 'c'}


>**(c)** Now we are ready to encode our message: “dancing is silent poetry”.


    >>> print swapdict('dancing is silent poetry', shiftdict(14))

In [250]:
print(swapdict('dancing is silent poetry', shiftdict(14)))

robqwbu wg gwzsbh dcshfm


>Check that it matches the encoding given above.


>**(d)** Write a function that takes a dictionary and swaps the roles of the keys and the values.


In [286]:
def invertdict(dictionary):
    #dictionary = {'a': 'b', 'b': 'c', 'c': 'd'}
    a=[]
    b=[]

    print(dictionary)

    for x,y in dictionary.items():
        a.append(y)
        b.append(x)

    t = zip(a, b)

        #print t

    otp_dict = dict((y, x) for y, x in t)
    #print(dict)
    return otp_dict

invertdict({'a': 'b', 'b': 'c', 'c': 'd'})

{'a': 'b', 'c': 'd', 'b': 'c'}


{'b': 'a', 'c': 'b', 'd': 'c'}

Here are some examples to check it works:

    >>> invertdict({'a':'b'})
    {'b': 'a'}
    >>> invertdict({'b':'a', 'a': 'b'})
    {'a': 'b', 'b': 'a'}
    >>> invertdict({'a':'b', 'b': 'c', 'c': 'a'})
    {'a': 'c', 'b': 'a','c': 'b'}

In [287]:
invertdict({'a':'b'})

{'a': 'b'}


{'b': 'a'}

>**(e)** Can you decode this message, that was encoded using the same scheme? “qzuipo nblft ju tjnqmf ipqfgvmmz”. Use only *invertdict*, *swapdict* and *shiftdict*.


In [300]:
print(swapdict('qzuipo nblft ju tjnqmf ipqfgvmmz', invert(shiftdict(-14))))



#print(swapdict('qzuipo nblft ju tjnqmf ipqfgvmmz', invertdict(shiftdict(-14))))

NameError: name 'invert' is not defined

>**(f)** You notice that your friend is sending encrypted messages to other people, but they appear to be encoded using a different argument to shiftdict.<br>
Use a for-loop, swapdict and shiftdict to work out the encoding scheme, and what this message says: “nyhcpaf pz aol yvva vm spnoaulzz”.


In [ ]:
# your code here